services:
  bookstoredb:
    image: mysql:8.0.0
    container_name: bookstoredb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: devuser
      MYSQL_PASSWORD: bookstoredb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --disable-ssl --skip-ssl

volumes:
  mysql_data:
